import { DomainError } from '../../common/errors.js';

export type VerificationStatus =
  | 'CREATED'
  | 'MESSAGE_SENT'
  | 'LINK_OPENED'
  | 'CONSENTED'
  | 'CUSTOMER_DATA_MISMATCH'
  | 'GPS_CAPTURING'
  | 'LOW_GPS_ACCURACY'
  | 'LOCATION_MISMATCH'
  | 'WAITING_FOR_HOME'
  | 'REMINDER_REQUIRED'
  | 'REMINDER_LIMIT_REACHED'
  | 'ADDRESS_EDITING'
  | 'ADDRESS_PROPOSED'
  | 'MANUAL_REVIEW'
  | 'LOCATION_VALID'
  | 'EXPIRED';

const transitions: Record<VerificationStatus, VerificationStatus[]> = {
  CREATED: ['MESSAGE_SENT', 'LINK_OPENED', 'WAITING_FOR_HOME', 'REMINDER_LIMIT_REACHED', 'EXPIRED'],
  MESSAGE_SENT: ['LINK_OPENED', 'CUSTOMER_DATA_MISMATCH', 'WAITING_FOR_HOME', 'REMINDER_LIMIT_REACHED', 'EXPIRED'],
  LINK_OPENED: [
    'CONSENTED',
    'CUSTOMER_DATA_MISMATCH',
    'ADDRESS_EDITING',
    'WAITING_FOR_HOME',
    'REMINDER_LIMIT_REACHED',
    'EXPIRED',
  ],
  CONSENTED: [
    'GPS_CAPTURING',
    'CUSTOMER_DATA_MISMATCH',
    'ADDRESS_EDITING',
    'WAITING_FOR_HOME',
    'REMINDER_LIMIT_REACHED',
    'EXPIRED',
  ],
  CUSTOMER_DATA_MISMATCH: ['ADDRESS_EDITING', 'EXPIRED'],
  GPS_CAPTURING: [
    'LOW_GPS_ACCURACY',
    'LOCATION_MISMATCH',
    'MANUAL_REVIEW',
    'LOCATION_VALID',
    'WAITING_FOR_HOME',
    'REMINDER_REQUIRED',
    'ADDRESS_EDITING',
    'EXPIRED',
  ],
  LOW_GPS_ACCURACY: [
    'GPS_CAPTURING',
    'WAITING_FOR_HOME',
    'REMINDER_REQUIRED',
    'REMINDER_LIMIT_REACHED',
    'ADDRESS_EDITING',
    'MANUAL_REVIEW',
    'LOCATION_MISMATCH',
    'LOCATION_VALID',
    'EXPIRED',
  ],
  LOCATION_MISMATCH: [
    'GPS_CAPTURING',
    'WAITING_FOR_HOME',
    'REMINDER_REQUIRED',
    'REMINDER_LIMIT_REACHED',
    'ADDRESS_EDITING',
    'MANUAL_REVIEW',
    'LOCATION_VALID',
    'EXPIRED',
  ],
  WAITING_FOR_HOME: [
    'CONSENTED',
    'CUSTOMER_DATA_MISMATCH',
    'GPS_CAPTURING',
    'REMINDER_REQUIRED',
    'REMINDER_LIMIT_REACHED',
    'ADDRESS_EDITING',
    'EXPIRED',
  ],
  REMINDER_REQUIRED: ['WAITING_FOR_HOME', 'REMINDER_LIMIT_REACHED', 'ADDRESS_EDITING', 'EXPIRED'],
  REMINDER_LIMIT_REACHED: ['CONSENTED', 'CUSTOMER_DATA_MISMATCH', 'GPS_CAPTURING', 'ADDRESS_EDITING', 'EXPIRED'],
  ADDRESS_EDITING: ['ADDRESS_PROPOSED', 'GPS_CAPTURING', 'EXPIRED'],
  ADDRESS_PROPOSED: [
    'CONSENTED',
    'CUSTOMER_DATA_MISMATCH',
    'ADDRESS_EDITING',
    'GPS_CAPTURING',
    'WAITING_FOR_HOME',
    'REMINDER_LIMIT_REACHED',
    'MANUAL_REVIEW',
    'LOCATION_VALID',
    'EXPIRED',
  ],
  MANUAL_REVIEW: [
    'GPS_CAPTURING',
    'LOCATION_MISMATCH',
    'REMINDER_REQUIRED',
    'ADDRESS_EDITING',
    'LOCATION_VALID',
    'EXPIRED',
  ],
  LOCATION_VALID: [],
  EXPIRED: [],
};

export function assertTransition(before: string, after: VerificationStatus): void {
  if (before === after) return;
  const allowed = transitions[before as VerificationStatus] ?? [];
  if (!allowed.includes(after))
    throw new DomainError(
      `Invalid verification status transition: ${before} -> ${after}`,
      409,
      'INVALID_STATE_TRANSITION',
    );
}
