import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'id' | 'en';

type TranslationKey = string;

const messages: Record<Language, Record<TranslationKey, string>> = {
  id: {
    'customers.addressIncomplete': 'Alamat belum lengkap — perlu dilengkapi/manual review',
    'detail.addressIncomplete': 'Alamat belum lengkap — koordinat tidak boleh dianggap sebagai bukti alamat lengkap.',
    'customer.requiredAddressFieldsWithPostal': 'Provinsi, kota, kecamatan, kelurahan, kode pos, jalan, dan nomor rumah wajib diisi.',
    'customer.gpsAutomatic': 'GPS sedang diambil otomatis. Mohon tunggu sebentar.',
    'customer.reminderDateTime': 'Pilih tanggal dan jam pengingat', 'customer.reminderTimezone': 'Waktu mengikuti zona waktu perangkat Anda.', 'customer.reminderInvalid': 'Pilih tanggal dan jam pengingat yang masih akan datang.',
    'customer.postalLookup': 'Isi otomatis', 'customer.postalLookupHint': 'Kode pos akan dicari otomatis setelah empat wilayah di atas terisi.', 'customer.postalLookupRequired': 'Lengkapi provinsi, kota/kabupaten, kecamatan, dan kelurahan/desa terlebih dahulu untuk mencari kode pos.', 'customer.postalLookupUnavailable': 'Pengisian kode pos otomatis tersedia pada link customer asli.', 'customer.postalLookupEmpty': 'Kode pos tidak ditemukan. Silakan isi secara manual.', 'customer.postalLookupFailed': 'Kode pos gagal dicari. Silakan isi secara manual.',
    'language.indonesian': 'Bahasa Indonesia', 'language.english': 'English', 'language.switch': 'Bahasa',
    'app.customerVerification': 'Verifikasi Lokasi', 'app.opsTitle': 'IRA Preregist Ops',
    'auth.portalSubtitle': 'Portal Validasi Customer & Verifikasi Dispatch', 'auth.sessionGuard': 'Better Auth Session Guard Aktif', 'auth.seedHint': 'Gunakan kredensial Better Auth yang dibuat melalui seed atau administrasi platform.', 'auth.companyEmail': 'Email Perusahaan', 'auth.password': 'Kata Sandi', 'auth.signingIn': 'Memverifikasi Sesi...', 'auth.signInDashboard': 'Masuk ke Dashboard Ops', 'auth.invalidCredentials': 'Autentikasi gagal. Silakan periksa email dan kata sandi Anda.', 'auth.emailPasswordRequired': 'Email dan kata sandi wajib diisi.', 'auth.emailCheck': 'Autentikasi gagal. Silakan periksa kembali email Anda.', 'auth.protectedBy': 'Dilindungi oleh Better Auth • PostgreSQL / PostGIS Spatial Engine',
    'nav.dashboard': 'Dashboard', 'nav.customers': 'Pelanggan & Alamat', 'nav.campaigns': 'Blasting Verifikasi', 'nav.verifications': 'Sesi Verifikasi', 'nav.reminders': 'Pengingat (Reminders)', 'nav.auditLogs': 'Audit Trail', 'nav.validationRules': 'Aturan Validasi', 'nav.integrations': 'Outbox & Integrasi',
    'dashboard.title': 'Ringkasan Operasional & Validasi Lokasi', 'dashboard.description': 'Monitoring verifikasi koordinat customer, kecocokan alamat, dan antrean manual review.', 'dashboard.apiUpdated': 'Data API diperbarui', 'dashboard.loading': 'memuat...', 'dashboard.refresh': 'Perbarui Data', 'dashboard.newVerification': 'Buat Sesi Verifikasi Baru', 'dashboard.waitingAtHome': 'Menunggu di Rumah', 'dashboard.lowAccuracy': 'Akurasi Rendah', 'dashboard.addressChanged': 'Alamat Berubah', 'dashboard.reminders': 'Pengingat (1 / 2 / 3)', 'dashboard.noGps': 'Belum ada tangkapan GPS', 'dashboard.detailMap': 'Detail & Peta', 'dashboard.totalCustomers': 'Total Pelanggan', 'dashboard.verified': 'sudah terverifikasi', 'dashboard.whatsappInvitations': 'Undangan WA', 'dashboard.linksOpened': 'link dibuka', 'dashboard.confirmedData': 'Data Terkonfirmasi', 'dashboard.mismatch': 'mismatch', 'dashboard.gpsCaptured': 'GPS Captured', 'dashboard.multiSample': 'Multi-sampel dari API', 'dashboard.manualReview': 'Manual Review', 'dashboard.addressQa': 'Address QA queue', 'dashboard.locationValid': 'Location Valid', 'dashboard.outboxEvents': 'outbox events', 'dashboard.funnel': 'Status Alur Verifikasi (Funnel Breakdown)', 'dashboard.totalSessions': 'Total Sesi', 'dashboard.recentSessions': 'Sesi Verifikasi Terbaru', 'dashboard.recentDescription': 'Gunakan tombol aksi untuk membuka detail verifikasi, peta visual, dan koordinat GPS.', 'dashboard.customer': 'Pelanggan', 'dashboard.phone': 'No. HP', 'dashboard.verificationStatus': 'Status Verifikasi', 'dashboard.gpsDistance': 'GPS & Jarak', 'dashboard.action': 'Aksi', 'dashboard.noSessions': 'Belum ada sesi verifikasi.', 'dashboard.noReference': 'Belum ada referensi',
    'customers.title': 'Master Pelanggan & Alamat Pemasangan', 'customers.description': 'Kelola data pelanggan, alamat referensi, dan proses verifikasi lokasi.', 'customers.import': 'Import Excel / CSV', 'customers.add': 'Tambah Satu Pelanggan', 'customers.search': 'Cari nama, ID, nomor HP, atau source ID...', 'customers.status': 'Status pelanggan', 'customers.allStatuses': 'Semua Status', 'customers.waitingInstallation': 'Menunggu pemasangan', 'customers.verified': 'Terverifikasi', 'customers.active': 'Aktif', 'customers.suspended': 'Ditangguhkan', 'customers.noAddress': 'Belum ada alamat', 'customers.newVerification': 'Buat sesi verifikasi baru', 'customers.viewDetail': 'Lihat detail pelanggan', 'customers.openGoogleMaps': 'Buka di Google Maps', 'customers.edit': 'Edit pelanggan', 'customers.deactivate': 'Nonaktifkan pelanggan', 'customers.editTitle': 'Edit Pelanggan & Alamat Master', 'customers.addTitle': 'Tambah Pelanggan Baru & Alamat Master', 'customers.fullName': 'Nama Lengkap', 'customers.externalId': 'ID Eksternal', 'customers.whatsapp': 'No. WhatsApp', 'customers.cancel': 'Batal', 'customers.saveChanges': 'Simpan Perubahan', 'customers.save': 'Simpan Pelanggan', 'customers.deactivateQuestion': 'Nonaktifkan pelanggan?', 'customers.confirmDeactivate': 'Ya, nonaktifkan', 'customers.confirmText': 'Pastikan pelanggan yang dipilih sudah benar sebelum melanjutkan.', 'customers.noPermanentDelete': 'Data tidak dihapus permanen dan tetap tersedia untuk riwayat audit.', 'customers.loadError': 'Data pelanggan gagal dimuat.', 'customers.invalidCoordinates': 'Latitude dan longitude wajib diisi dengan koordinat yang valid.', 'customers.saveError': 'Data pelanggan gagal disimpan.', 'customers.noReference': 'Pelanggan ini belum memiliki alamat aktif dengan koordinat referensi.', 'customers.deleteError': 'Pelanggan gagal dinonaktifkan.', 'detail.notFound': 'Pelanggan tidak ditemukan.', 'detail.back': 'Kembali', 'detail.customerId': 'ID pelanggan', 'detail.registeredSince': 'Terdaftar sejak', 'detail.addresses': 'Daftar Alamat Pelanggan', 'detail.sessions': 'Riwayat Sesi Verifikasi', 'detail.generate': 'Generate Sesi Verifikasi Baru', 'detail.noSessions': 'Belum ada sesi verifikasi untuk pelanggan ini.', 'detail.openMap': 'Buka Detail Peta & Validasi', 'detail.openGoogleMaps': 'Buka Google Maps',
    'verifications.title': 'Daftar Sesi Verifikasi Lokasi', 'verifications.description': 'Monitoring seluruh verification session, state machine, percobaan GPS, dan status pengingat.', 'verifications.refresh': 'Muat ulang', 'verifications.search': 'Cari sesi, nama customer, nomor HP...', 'verifications.filterStatus': 'Filter Status', 'verifications.allStatuses': 'Semua Status', 'verifications.noGps': 'Belum ada tangkapan GPS', 'verifications.detail': 'Detail', 'verifications.loadError': 'Daftar sesi gagal dimuat.',
    'reminders.title': 'Riwayat & Antrean Pengingat WhatsApp', 'reminders.description': 'Manajemen pengingat otomatis dengan batasan maksimal per sesi pelanggan.', 'reminders.refresh': 'Muat ulang pengingat', 'reminders.search': 'Cari pelanggan, nomor HP, atau sesi...', 'reminders.allStatuses': 'Semua status', 'reminders.loadError': 'Daftar pengingat gagal dimuat.',
    'audit.title': 'Audit Trail & Kepatuhan Operasional', 'audit.description': 'Log seluruh interaksi sistem, GPS captures, audit event, dan keputusan review manual.', 'audit.total': 'Total Log', 'audit.entries': 'entri', 'audit.refresh': 'Muat ulang audit trail', 'audit.search': 'Cari aksi, nama actor, entity ID, alasan...', 'audit.actor': 'Actor', 'audit.entity': 'Entity', 'audit.all': 'Semua', 'audit.loadError': 'Audit trail gagal dimuat.',
    'campaigns.title': 'Blasting Verifikasi WhatsApp', 'campaigns.description': 'Kirim undangan verifikasi bertahap melalui queue. Fitur ini untuk verifikasi, bukan campaign promosi.', 'campaigns.name': 'Nama blasting', 'campaigns.batchSize': 'Ukuran batch worker', 'campaigns.window': 'Window blasting (hari)', 'campaigns.defaultWindow': 'Default 7 hari; rate limit provider tetap berlaku.', 'campaigns.searchCustomer': 'Cari nama, ID, atau nomor HP customer...', 'campaigns.findCustomer': 'Cari customer', 'campaigns.selectPage': 'Pilih semua pada halaman ini', 'campaigns.selectAllEligible': 'Pilih semua customer eligible', 'campaigns.selected': 'Terpilih', 'campaigns.loadingTargets': 'Memuat target yang belum terverifikasi...', 'campaigns.process': 'Memproses...', 'campaigns.createStart': 'Buat & mulai blasting', 'campaigns.history': 'Riwayat Blasting', 'campaigns.loading': 'Memuat blasting...', 'campaigns.empty': 'Belum ada blasting.', 'campaigns.start': 'Mulai', 'campaigns.refresh': 'Muat ulang blasting',
    'settings.title': 'Konfigurasi Aturan Mesin Validasi', 'settings.readOnly': 'Read Only', 'settings.saved': 'Konfigurasi berhasil diperbarui dan diterapkan ke mesin validasi spasial.', 'settings.spatial': 'Parameter Spasial & GPS Device', 'settings.session': 'Masa Berlaku Sesi & Batas Pengingat', 'settings.features': 'Feature Flags & Modul Operasional', 'settings.save': 'Simpan Perubahan Aturan',
    'integrations.title': 'Event Outbox & Kontrak Integrasi Eksternal', 'integrations.reload': 'Muat ulang outbox', 'integrations.search': 'Cari event, aggregate, atau correlation ID...', 'integrations.allStatuses': 'Semua status', 'integrations.loading': 'Memuat outbox...', 'integrations.loadError': 'Outbox gagal dimuat.',
    'shell.verifiedLocations': 'Lokasi Terverifikasi', 'shell.needsReview': 'Perlu Ditinjau', 'shell.radius': 'Radius', 'shell.accuracy': 'Akurasi', 'shell.theme': 'Tema Tampilan', 'shell.light': 'Terang', 'shell.dark': 'Gelap', 'shell.system': 'Sistem (Auto)', 'shell.logout': 'Keluar Sesi (Logout)', 'shell.online': 'Online', 'shell.ready': 'Ready', 'table.show': 'Tampilkan', 'table.perPage': 'data per halaman', 'table.of': 'dari', 'table.previous': 'Halaman sebelumnya', 'table.next': 'Halaman berikutnya', 'table.openPage': 'Buka halaman', 'table.navigation': 'Navigasi halaman tabel', 'table.customerId': 'ID Pelanggan', 'table.customerName': 'Nama Pelanggan', 'table.whatsapp': 'Nomor WhatsApp', 'table.address': 'Alamat Terdaftar', 'table.latitude': 'Latitude', 'table.longitude': 'Longitude', 'table.coverage': 'Coverage / BTS', 'table.status': 'Status', 'table.action': 'Aksi', 'table.sessionCustomer': 'Sesi ID & Pelanggan', 'table.verificationStatus': 'Status Verifikasi', 'table.gpsDistance': 'Hasil GPS & Jarak', 'table.attempts': 'Percobaan', 'table.reminders': 'Pengingat (Max 3)', 'table.reminderOrder': 'Urutan Pengingat', 'table.channelTarget': 'Channel & Target', 'table.schedule': 'Jadwal / Waktu Kirim', 'table.openSession': 'Buka Sesi', 'table.loadingSessions': 'Memuat sesi...', 'table.noMatchingSessions': 'Tidak ada sesi yang sesuai.', 'table.loadingReminders': 'Memuat pengingat...', 'table.noReminders': 'Belum ada pengingat.', 'table.campaign': 'Campaign', 'table.target': 'Target', 'table.materialization': 'Materialisasi', 'table.sent': 'Terkirim', 'table.failed': 'Gagal', 'table.deliveryStatus': 'Status pengiriman', 'table.retry': 'Retry', 'table.providerMessage': 'Pesan provider',
    'customer.verification': 'Verifikasi Lokasi', 'customer.invalidLink': 'Tautan tidak valid', 'customer.loading': 'Memuat verifikasi...', 'customer.hello': 'Halo', 'customer.confirmLocation': 'Konfirmasi lokasi pemasangan', 'customer.confirmData': 'Apakah data dan alamat di atas benar milik Anda?', 'customer.stillAtAddress': 'Sebelum melanjutkan, apakah Anda masih tinggal di alamat ini?', 'customer.registeredAddress': 'Alamat terdaftar', 'customer.phone': 'Telepon', 'customer.locationPermission': 'Kami membutuhkan izin lokasi browser untuk memvalidasi Anda berada di alamat tersebut. Pastikan Anda sudah berada di rumah, jika belum bisa ke bagian bawah untuk pasang reminder yang akan diingatkan lagi untuk verifikasi-nya', 'customer.allowAndStart': 'Izinkan dan mulai verifikasi GPS', 'customer.notMyData': 'Bukan data saya', 'customer.yesCorrect': 'Ya, benar', 'customer.previousMismatch': 'Hasil sebelumnya belum sesuai', 'customer.retryGps': 'Saya sudah di rumah, coba GPS ulang', 'customer.addressChanged': 'Alamat saya berubah', 'customer.gpsSamples': 'Ambil 3 sampel GPS. Sistem akan memilih sampel dengan akurasi terbaik di backend.', 'customer.captureLocation': 'Ambil 3 sampel lokasi', 'customer.requestNewAddress': 'Ajukan alamat baru', 'customer.submitAddress': 'Ajukan alamat untuk verifikasi ulang', 'customer.waitingAtHome': 'Menunggu Anda tiba di rumah', 'customer.reminderScheduled': 'Pengingat telah dijadwalkan. Buka kembali tautan ini saat sudah di lokasi.', 'customer.reminderLimit': 'Batas pengingat tercapai', 'customer.returnToLink': 'Silakan kembali ke link ini saat sudah berada di lokasi.', 'customer.newAddressSubmitted': 'Alamat baru diajukan', 'customer.addressWaitingGps': 'Alamat baru tetap menunggu verifikasi GPS.', 'customer.manualReview': 'Sedang ditinjau tim Ops', 'customer.manualReviewText': 'Data GPS sudah diterima dan membutuhkan pemeriksaan manual.', 'customer.dataNeedsUpdate': 'Data perlu diperbarui', 'customer.contactSupport': 'Silakan ajukan alamat terbaru atau hubungi customer service.', 'customer.locationVerified': 'Lokasi berhasil diverifikasi', 'customer.addressValidated': 'Alamat dan titik lokasi pemasangan telah tervalidasi.', 'customer.doNotShareLink': 'Jangan bagikan tautan verifikasi ini', 'customer.askReminder': 'Ingatkan saya', 'customer.reminderTime': 'Pilih waktu pengingat', 'customer.oneHour': '1 jam lagi', 'customer.tonight': 'Malam ini', 'customer.tomorrowMorning': 'Besok pagi', 'customer.requestGpsAgain': 'Coba minta izin GPS lagi', 'customer.browserNoLocation': 'Browser tidak mendukung pengambilan lokasi.', 'customer.permissionDenied': 'Izin lokasi ditolak. Tekan coba lagi. Jika browser tidak menampilkan permintaan izin, buka pengaturan izin lokasi untuk situs ini lalu aktifkan kembali.', 'customer.requestFailed': 'Permintaan tidak dapat diproses.', 'customer.requiredAddressFields': 'Provinsi, kota, kecamatan, kelurahan, jalan, dan nomor rumah wajib diisi.',
    'customer.manualReviewNotice': 'Pemeriksaan otomatis sudah selesai dan data lokasi diterima. Lokasi belum dinyatakan berhasil karena tim kami sedang melakukan verifikasi manual. Tidak perlu mengulang selama belum diminta.',
  },
  en: {
    'customers.addressIncomplete': 'Address incomplete — needs completion/manual review',
    'detail.addressIncomplete': 'Address incomplete — coordinates must not be treated as proof of a complete address.',
    'customer.requiredAddressFieldsWithPostal': 'Province, city, district, subdistrict, postal code, street, and house number are required.',
    'customer.gpsAutomatic': 'GPS is being captured automatically. Please wait a moment.',
    'customer.reminderDateTime': 'Choose reminder date and time', 'customer.reminderTimezone': 'Time follows your device timezone.', 'customer.reminderInvalid': 'Choose a reminder date and time in the future.',
    'customer.postalLookup': 'Auto-fill', 'customer.postalLookupHint': 'The postal code will be looked up automatically after the four region fields above are filled.', 'customer.postalLookupRequired': 'Complete province, city/regency, district, and village first to find the postal code.', 'customer.postalLookupUnavailable': 'Automatic postal code lookup is available on the real customer link.', 'customer.postalLookupEmpty': 'Postal code not found. Please enter it manually.', 'customer.postalLookupFailed': 'Postal code lookup failed. Please enter it manually.',
    'language.indonesian': 'Bahasa Indonesia', 'language.english': 'English', 'language.switch': 'Language',
    'app.customerVerification': 'Location Verification', 'app.opsTitle': 'IRA Preregist Ops',
    'auth.portalSubtitle': 'Customer Validation & Dispatch Verification Portal', 'auth.sessionGuard': 'Better Auth Session Guard Active', 'auth.seedHint': 'Use the Better Auth credentials created through seed or platform administration.', 'auth.companyEmail': 'Company Email', 'auth.password': 'Password', 'auth.signingIn': 'Verifying Session...', 'auth.signInDashboard': 'Sign in to Ops Dashboard', 'auth.invalidCredentials': 'Authentication failed. Please check your email and password.', 'auth.emailPasswordRequired': 'Email and password are required.', 'auth.emailCheck': 'Authentication failed. Please check your email again.', 'auth.protectedBy': 'Protected by Better Auth • PostgreSQL / PostGIS Spatial Engine',
    'nav.dashboard': 'Dashboard', 'nav.customers': 'Customers & Addresses', 'nav.campaigns': 'Verification Blast', 'nav.verifications': 'Verification Sessions', 'nav.reminders': 'Reminders', 'nav.auditLogs': 'Audit Trail', 'nav.validationRules': 'Validation Rules', 'nav.integrations': 'Outbox & Integrations',
    'dashboard.title': 'Operations & Location Validation Overview', 'dashboard.description': 'Monitor customer coordinate verification, address matching, and the manual review queue.', 'dashboard.apiUpdated': 'API data updated', 'dashboard.loading': 'loading...', 'dashboard.refresh': 'Refresh Data', 'dashboard.newVerification': 'Create New Verification Session', 'dashboard.waitingAtHome': 'Waiting at Home', 'dashboard.lowAccuracy': 'Low Accuracy', 'dashboard.addressChanged': 'Address Changed', 'dashboard.reminders': 'Reminders (1 / 2 / 3)', 'dashboard.noGps': 'No GPS capture yet', 'dashboard.detailMap': 'Details & Map', 'dashboard.totalCustomers': 'Total Customers', 'dashboard.verified': 'verified', 'dashboard.whatsappInvitations': 'WA Invitations', 'dashboard.linksOpened': 'links opened', 'dashboard.confirmedData': 'Confirmed Data', 'dashboard.mismatch': 'mismatch', 'dashboard.gpsCaptured': 'GPS Captured', 'dashboard.multiSample': 'Multi-sample from API', 'dashboard.manualReview': 'Manual Review', 'dashboard.addressQa': 'Address QA queue', 'dashboard.locationValid': 'Location Valid', 'dashboard.outboxEvents': 'outbox events', 'dashboard.funnel': 'Verification Flow Status (Funnel Breakdown)', 'dashboard.totalSessions': 'Total Sessions', 'dashboard.recentSessions': 'Recent Verification Sessions', 'dashboard.recentDescription': 'Use the action button to open verification details, the visual map, and GPS coordinates.', 'dashboard.customer': 'Customer', 'dashboard.phone': 'Phone', 'dashboard.verificationStatus': 'Verification Status', 'dashboard.gpsDistance': 'GPS & Distance', 'dashboard.action': 'Action', 'dashboard.noSessions': 'No verification sessions yet.', 'dashboard.noReference': 'No reference yet',
    'customers.title': 'Customer & Installation Address Master', 'customers.description': 'Manage customer data, reference addresses, and location verification.', 'customers.import': 'Import Excel / CSV', 'customers.add': 'Add One Customer', 'customers.search': 'Search name, ID, phone number, or source ID...', 'customers.status': 'Customer status', 'customers.allStatuses': 'All Statuses', 'customers.waitingInstallation': 'Waiting for installation', 'customers.verified': 'Verified', 'customers.active': 'Active', 'customers.suspended': 'Suspended', 'customers.noAddress': 'No address yet', 'customers.newVerification': 'Create new verification session', 'customers.viewDetail': 'View customer details', 'customers.openGoogleMaps': 'Open in Google Maps', 'customers.edit': 'Edit customer', 'customers.deactivate': 'Deactivate customer', 'customers.editTitle': 'Edit Customer & Master Address', 'customers.addTitle': 'Add New Customer & Master Address', 'customers.fullName': 'Full Name', 'customers.externalId': 'External ID', 'customers.whatsapp': 'WhatsApp Number', 'customers.cancel': 'Cancel', 'customers.saveChanges': 'Save Changes', 'customers.save': 'Save Customer', 'customers.deactivateQuestion': 'Deactivate customer?', 'customers.confirmDeactivate': 'Yes, deactivate', 'customers.confirmText': 'Make sure the selected customer is correct before continuing.', 'customers.noPermanentDelete': 'The data is not permanently deleted and remains available for audit history.', 'customers.loadError': 'Customer data could not be loaded.', 'customers.invalidCoordinates': 'Latitude and longitude must be valid coordinates.', 'customers.saveError': 'Customer data could not be saved.', 'customers.noReference': 'This customer has no active address with reference coordinates.', 'customers.deleteError': 'Customer could not be deactivated.', 'detail.notFound': 'Customer not found.', 'detail.back': 'Back', 'detail.customerId': 'Customer ID', 'detail.registeredSince': 'Registered since', 'detail.addresses': 'Customer Addresses', 'detail.sessions': 'Verification Session History', 'detail.generate': 'Generate New Verification Session', 'detail.noSessions': 'No verification sessions for this customer.', 'detail.openMap': 'Open Map Details & Validation', 'detail.openGoogleMaps': 'Open Google Maps',
    'verifications.title': 'Location Verification Sessions', 'verifications.description': 'Monitor all verification sessions, state machine, GPS attempts, and reminder status.', 'verifications.refresh': 'Refresh', 'verifications.search': 'Search session, customer name, phone number...', 'verifications.filterStatus': 'Filter Status', 'verifications.allStatuses': 'All Statuses', 'verifications.noGps': 'No GPS capture yet', 'verifications.detail': 'Details', 'verifications.loadError': 'Verification sessions could not be loaded.',
    'reminders.title': 'WhatsApp Reminder History & Queue', 'reminders.description': 'Manage automated reminders with a maximum limit per customer session.', 'reminders.refresh': 'Refresh reminders', 'reminders.search': 'Search customer, phone number, or session...', 'reminders.allStatuses': 'All statuses', 'reminders.loadError': 'Reminders could not be loaded.',
    'audit.title': 'Audit Trail & Operational Compliance', 'audit.description': 'Log all system interactions, GPS captures, audit events, and manual review decisions.', 'audit.total': 'Total Logs', 'audit.entries': 'entries', 'audit.refresh': 'Refresh audit trail', 'audit.search': 'Search action, actor name, entity ID, reason...', 'audit.actor': 'Actor', 'audit.entity': 'Entity', 'audit.all': 'All', 'audit.loadError': 'Audit trail could not be loaded.',
    'campaigns.title': 'WhatsApp Verification Blast', 'campaigns.description': 'Send verification invitations in stages through the queue. This feature is for verification, not promotional campaigns.', 'campaigns.name': 'Blast name', 'campaigns.batchSize': 'Worker batch size', 'campaigns.window': 'Blast window (days)', 'campaigns.defaultWindow': 'Default 7 days; provider rate limits still apply.', 'campaigns.searchCustomer': 'Search customer name, ID, or phone number...', 'campaigns.findCustomer': 'Find customers', 'campaigns.selectPage': 'Select all on this page', 'campaigns.selectAllEligible': 'Select all eligible customers', 'campaigns.selected': 'Selected', 'campaigns.loadingTargets': 'Loading unverified targets...', 'campaigns.process': 'Processing...', 'campaigns.createStart': 'Create & start blast', 'campaigns.history': 'Blast History', 'campaigns.loading': 'Loading blasts...', 'campaigns.empty': 'No blasts yet.', 'campaigns.start': 'Start', 'campaigns.refresh': 'Refresh blasts',
    'settings.title': 'Validation Engine Rules Configuration', 'settings.readOnly': 'Read Only', 'settings.saved': 'Configuration updated and applied to the spatial validation engine.', 'settings.spatial': 'Spatial & GPS Device Parameters', 'settings.session': 'Session Lifetime & Reminder Limits', 'settings.features': 'Feature Flags & Operations Modules', 'settings.save': 'Save Rule Changes',
    'integrations.title': 'External Integration Event Outbox & Contract', 'integrations.reload': 'Refresh outbox', 'integrations.search': 'Search event, aggregate, or correlation ID...', 'integrations.allStatuses': 'All statuses', 'integrations.loading': 'Loading outbox...', 'integrations.loadError': 'Outbox could not be loaded.',
    'shell.verifiedLocations': 'Verified Locations', 'shell.needsReview': 'Needs Review', 'shell.radius': 'Radius', 'shell.accuracy': 'Accuracy', 'shell.theme': 'Display Theme', 'shell.light': 'Light', 'shell.dark': 'Dark', 'shell.system': 'System (Auto)', 'shell.logout': 'Log out', 'shell.online': 'Online', 'shell.ready': 'Ready', 'table.show': 'Show', 'table.perPage': 'items per page', 'table.of': 'of', 'table.previous': 'Previous page', 'table.next': 'Next page', 'table.openPage': 'Open page', 'table.navigation': 'Table page navigation', 'table.customerId': 'Customer ID', 'table.customerName': 'Customer Name', 'table.whatsapp': 'WhatsApp Number', 'table.address': 'Registered Address', 'table.latitude': 'Latitude', 'table.longitude': 'Longitude', 'table.coverage': 'Coverage / BTS', 'table.status': 'Status', 'table.action': 'Action', 'table.sessionCustomer': 'Session ID & Customer', 'table.verificationStatus': 'Verification Status', 'table.gpsDistance': 'GPS Result & Distance', 'table.attempts': 'Attempts', 'table.reminders': 'Reminders (Max 3)', 'table.reminderOrder': 'Reminder Order', 'table.channelTarget': 'Channel & Target', 'table.schedule': 'Schedule / Send Time', 'table.openSession': 'Open Session', 'table.loadingSessions': 'Loading sessions...', 'table.noMatchingSessions': 'No matching sessions.', 'table.loadingReminders': 'Loading reminders...', 'table.noReminders': 'No reminders yet.', 'table.campaign': 'Campaign', 'table.target': 'Target', 'table.materialization': 'Materialization', 'table.sent': 'Sent', 'table.failed': 'Failed', 'table.deliveryStatus': 'Delivery status', 'table.retry': 'Retry', 'table.providerMessage': 'Provider message',
    'customer.verification': 'Location Verification', 'customer.invalidLink': 'Invalid link', 'customer.loading': 'Loading verification...', 'customer.hello': 'Hello', 'customer.confirmLocation': 'Confirm installation location', 'customer.confirmData': 'Is the data and address above yours?', 'customer.stillAtAddress': 'Before continuing, do you still live at this address?', 'customer.registeredAddress': 'Registered address', 'customer.phone': 'Phone', 'customer.locationPermission': 'We need your browser location permission to verify that you are at this address.', 'customer.allowAndStart': 'Allow and start GPS verification', 'customer.notMyData': 'This is not my data', 'customer.yesCorrect': 'Yes, correct', 'customer.previousMismatch': 'The previous result did not match', 'customer.retryGps': "I'm at home, retry GPS", 'customer.addressChanged': 'My address has changed', 'customer.gpsSamples': 'Capture 3 GPS samples. The backend will choose the sample with the best accuracy.', 'customer.captureLocation': 'Capture 3 location samples', 'customer.requestNewAddress': 'Submit a new address', 'customer.submitAddress': 'Submit address for re-verification', 'customer.waitingAtHome': 'Waiting for you to arrive home', 'customer.reminderScheduled': 'A reminder has been scheduled. Reopen this link when you are at the location.', 'customer.reminderLimit': 'Reminder limit reached', 'customer.returnToLink': 'Return to this link when you are at the location.', 'customer.newAddressSubmitted': 'New address submitted', 'customer.addressWaitingGps': 'The new address is still waiting for GPS verification.', 'customer.manualReview': 'Under Ops team review', 'customer.manualReviewText': 'GPS data has been received and requires manual review.', 'customer.dataNeedsUpdate': 'Data needs to be updated', 'customer.contactSupport': 'Please submit your latest address or contact customer service.', 'customer.locationVerified': 'Location successfully verified', 'customer.addressValidated': 'The installation address and location have been verified.', 'customer.doNotShareLink': 'Do not share this verification link', 'customer.askReminder': 'Remind me', 'customer.reminderTime': 'Choose reminder time', 'customer.oneHour': 'In 1 hour', 'customer.tonight': 'Tonight', 'customer.tomorrowMorning': 'Tomorrow morning', 'customer.requestGpsAgain': 'Request GPS permission again', 'customer.browserNoLocation': 'This browser does not support location capture.', 'customer.permissionDenied': 'Location permission was denied. Try again. If the browser does not show a permission prompt, open this site\'s location permissions and enable it.', 'customer.requestFailed': 'The request could not be processed.', 'customer.requiredAddressFields': 'Province, city, district, subdistrict, street, and house number are required.',
    'customer.manualReviewNotice': 'The automated check is complete and your location data was received. It is not marked as verified yet because our team is performing a manual review. Please do not repeat the process unless requested.',
  },
};

const extraMessages: Record<Language, Record<string, string>> = {
  id: {
    'table.signal': 'Sinyal / Parameter', 'table.masterReference': 'Data Referensi Master', 'table.deviceGeo': 'Data Perangkat / Reverse Geo', 'table.evaluation': 'Hasil Evaluasi', 'settings.description': 'Pengaturan ambang batas, toleransi GPS, bobot skoring alamat, dan feature flags.', 'settings.gpsAccuracy': 'Batas Akurasi Maksimal GPS', 'settings.gpsAccuracyHelp': 'Tangkapan GPS dengan akurasi di atas nilai ini akan ditolak.', 'settings.homeRadius': 'Toleransi Radius Rumah', 'settings.homeRadiusHelp': 'Jarak antara koordinat referensi master dan titik customer.', 'settings.streetMatch': 'Threshold Kecocokan Nama Jalan', 'settings.streetMatchHelp': 'Skor kemiripan nama jalan menggunakan Jaro-Winkler/Levenshtein.', 'settings.addressScore': 'Threshold Total Skor Alamat', 'settings.addressScoreHelp': 'Bobot: Kecamatan 20%, Kelurahan 25%, Jalan 35%, Nomor 20%.', 'settings.maxReminders': 'Maksimal Pengingat / Sesi', 'settings.tokenLifetime': 'Masa Berlaku Token (Hari)', 'settings.decimalPrecision': 'Presisi Tampilan Desimal', 'settings.strictReminder': 'Batas ketat 3x pengingat.', 'settings.defaultExpiry': 'Default kedaluwarsa 7 hari.',
    'integrations.description': 'Publikasikan domain event dengan idempotency key dan correlation tracking.', 'integrations.outboxCount': 'Outbox: {count} Events', 'integrations.coverageSubtitle': 'Fiber Polygon & FAT Capacity Check', 'integrations.coverageDescription': 'Menyediakan antarmuka standar untuk query coverage map setelah exact coordinate terverifikasi.', 'integrations.ticketSubtitle': 'Work Order & Field Technician SLA', 'integrations.ticketDescription': 'Menerima event terverifikasi untuk trigger pembuatan Surat Tugas dan reservasi teknisi pasang baru.', 'integrations.streamDescription': 'Event payload terbit otomatis saat lokasi dinyatakan valid.', 'integrations.payload': 'Payload Data (JSON)', 'integrations.empty': 'Belum ada event yang dipublikasikan. Selesaikan verifikasi lokasi untuk melihat payload Outbox.',
    'reminders.sent': 'Terkirim', 'reminders.scheduled': 'Terjadwal', 'reminders.number': 'Pengingat #{number}',
    'campaigns.status.DRAFT': 'Draft', 'campaigns.status.RUNNING': 'Berjalan', 'campaigns.status.PAUSED': 'Dijeda', 'campaigns.status.COMPLETED': 'Selesai', 'campaigns.itemStatus.PENDING': 'Menunggu', 'campaigns.itemStatus.PROCESSING': 'Diproses', 'campaigns.itemStatus.SENT': 'Diterima provider', 'campaigns.itemStatus.DELIVERED': 'Terkirim', 'campaigns.itemStatus.READ': 'Dibaca', 'campaigns.itemStatus.FAILED': 'Gagal', 'campaigns.itemStatus.PROVIDER_UNAVAILABLE': 'Provider tidak tersedia', 'campaigns.itemStatus.OPTED_OUT': 'Opt-out', 'campaigns.targetEmpty': 'Tidak ada customer yang belum terverifikasi GPS pada halaman ini.', 'campaigns.info': 'Pilih semua eligible memakai filter backend dan diproses worker per batch. Sistem tetap memblokir customer opt-out dan provider yang tidak tersedia tidak dianggap berhasil.', 'campaigns.processing': 'Memproses...', 'campaigns.createStart': 'Buat & mulai campaign', 'campaigns.created': 'Campaign dibuat dan dijadwalkan untuk {count} customer.', 'campaigns.itemLoadError': 'Status item tidak dapat dimuat.', 'campaigns.deliveryTitle': 'Status pengiriman per customer', 'campaigns.itemsDescription': 'Item ditampilkan secara paginasi agar campaign besar tidak dimuat sekaligus.', 'campaigns.defaultCustomer': 'Customer', 'campaigns.noItems': 'Belum ada item.', 'campaigns.defaultName': 'Verifikasi Lokasi', 'campaigns.days': 'hari', 'campaigns.eligible': 'eligible',
    'settings.feature.manualReview': 'Aktifkan Antrean Review Manual (Ops QA)', 'settings.feature.manualReviewDesc': 'Memungkinkan reviewer melakukan bypass, approve, atau reject hasil verifikasi.', 'settings.feature.addressEdit': 'Izinkan Pelanggan Usulkan Alamat Baru (PROPOSED)', 'settings.feature.addressEditDesc': 'Jika rumah pindah, pelanggan dapat mengedit teks alamat pada web flow.', 'settings.feature.reminders': 'Otomasi Pengingat WhatsApp', 'settings.feature.remindersDesc': 'Kirim reminder terjadwal 1x24 jam, 2x24 jam jika customer belum buka link.', 'settings.feature.iraCoverage': 'Integrasi IRA Coverage (Port Ready)', 'settings.feature.iraCoverageDesc': 'Koneksi ke port IRA GIS untuk pengecekan kapasitas FAT dan polygon.', 'settings.feature.ticketing': 'Integrasi Ticketing Dispatch (Port Ready)', 'settings.feature.ticketingDesc': 'Koneksi ke port sistem tiket instalasi teknisi lapangan.', 'settings.decimalPrecisionHelp': 'Standar GPS: 6 desimal.',
  },
  en: {
    'table.signal': 'Signal / Parameter', 'table.masterReference': 'Master Reference Data', 'table.deviceGeo': 'Device / Reverse Geo Data', 'table.evaluation': 'Evaluation Result', 'settings.description': 'Configure thresholds, GPS tolerance, address scoring weights, and feature flags.', 'settings.gpsAccuracy': 'Maximum GPS Accuracy', 'settings.gpsAccuracyHelp': 'GPS captures above this accuracy value will be rejected.', 'settings.homeRadius': 'Home Radius Tolerance', 'settings.homeRadiusHelp': 'Distance between the master reference coordinate and the customer point.', 'settings.streetMatch': 'Street Name Match Threshold', 'settings.streetMatchHelp': 'Street name similarity score using Jaro-Winkler/Levenshtein.', 'settings.addressScore': 'Total Address Score Threshold', 'settings.addressScoreHelp': 'Weights: District 20%, Subdistrict 25%, Street 35%, Number 20%.', 'settings.maxReminders': 'Maximum Reminders / Session', 'settings.tokenLifetime': 'Token Lifetime (Days)', 'settings.decimalPrecision': 'Decimal Display Precision', 'settings.strictReminder': 'Strict limit: 3 reminders.', 'settings.defaultExpiry': 'Default expiration: 7 days.',
    'integrations.description': 'Publish domain events with idempotency keys and correlation tracking.', 'integrations.outboxCount': 'Outbox: {count} Events', 'integrations.coverageSubtitle': 'Fiber Polygon & FAT Capacity Check', 'integrations.coverageDescription': 'Provides an interface for querying the coverage map after the exact coordinate is verified.', 'integrations.ticketSubtitle': 'Work Order & Field Technician SLA', 'integrations.ticketDescription': 'Receives verified events to trigger work order creation and new-installation technician reservations.', 'integrations.streamDescription': 'Event payloads are published automatically when a location is declared valid.', 'integrations.payload': 'Payload Data (JSON)', 'integrations.empty': 'No events have been published. Complete a location verification to view the Outbox payload.',
    'reminders.sent': 'Sent', 'reminders.scheduled': 'Scheduled', 'reminders.number': 'Reminder #{number}',
    'campaigns.status.DRAFT': 'Draft', 'campaigns.status.RUNNING': 'Running', 'campaigns.status.PAUSED': 'Paused', 'campaigns.status.COMPLETED': 'Completed', 'campaigns.itemStatus.PENDING': 'Pending', 'campaigns.itemStatus.PROCESSING': 'Processing', 'campaigns.itemStatus.SENT': 'Accepted by provider', 'campaigns.itemStatus.DELIVERED': 'Delivered', 'campaigns.itemStatus.READ': 'Read', 'campaigns.itemStatus.FAILED': 'Failed', 'campaigns.itemStatus.PROVIDER_UNAVAILABLE': 'Provider unavailable', 'campaigns.itemStatus.OPTED_OUT': 'Opt-out', 'campaigns.targetEmpty': 'No customers without GPS verification on this page.', 'campaigns.info': 'Select all eligible customers using the backend filter and process them in worker batches. Opt-outs remain blocked, and unavailable providers are not counted as successful.', 'campaigns.processing': 'Processing...', 'campaigns.createStart': 'Create & start campaign', 'campaigns.created': 'Campaign created and scheduled for {count} customers.', 'campaigns.itemLoadError': 'Campaign item status could not be loaded.', 'campaigns.deliveryTitle': 'Delivery status per customer', 'campaigns.itemsDescription': 'Items are paginated so large campaigns are not loaded all at once.', 'campaigns.defaultCustomer': 'Customer', 'campaigns.noItems': 'No items yet.', 'campaigns.defaultName': 'Location Verification', 'campaigns.days': 'days', 'campaigns.eligible': 'eligible',
    'settings.feature.manualReview': 'Enable Manual Review Queue (Ops QA)', 'settings.feature.manualReviewDesc': 'Allows reviewers to bypass, approve, or reject verification results.', 'settings.feature.addressEdit': 'Allow Customers to Propose a New Address (PROPOSED)', 'settings.feature.addressEditDesc': 'If a customer moves, they can edit the address text in the web flow.', 'settings.feature.reminders': 'WhatsApp Reminder Automation', 'settings.feature.remindersDesc': 'Send scheduled reminders after 1x24 hours and 2x24 hours if the customer has not opened the link.', 'settings.feature.iraCoverage': 'IRA Coverage Integration (Port Ready)', 'settings.feature.iraCoverageDesc': 'Connects to the IRA GIS port to check FAT and polygon capacity.', 'settings.feature.ticketing': 'Dispatch Ticketing Integration (Port Ready)', 'settings.feature.ticketingDesc': 'Connects to the field technician installation ticketing system.', 'settings.decimalPrecisionHelp': 'GPS standard: 6 decimal places.',
  },
};

interface I18nContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
}

const I18nContext = createContext<I18nContextValue | null>(null);

export const I18nProvider: React.FC<{ children: React.ReactNode; defaultLanguage?: Language }> = ({ children, defaultLanguage }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (defaultLanguage) return defaultLanguage;
    const saved = localStorage.getItem('el_language');
    return saved === 'en' || saved === 'id' ? saved : 'en';
  });
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const setLanguage = (next: Language) => {
    setLanguageState(next);
    localStorage.setItem('el_language', next);
    document.documentElement.lang = next;
  };
  const value = useMemo<I18nContextValue>(() => ({
    language, setLanguage, t: (key, values) => {
      const template = messages[language][key] ?? extraMessages[language][key] ?? key;
      return Object.entries(values ?? {}).reduce((result, [name, value]) => result.replaceAll(`{${name}}`, String(value)), template);
    }
  }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
};

export const useTranslation = () => {
  const context = useContext(I18nContext);
  if (!context) throw new Error('useTranslation must be used within I18nProvider');
  return context;
};
